class FormatParams: 
    """
    doc
    """
    def __init__(self, params, data):
        self.per = params[data.par_order['per']*data.nvisit:(1 + data.par_order['per'])*data.nvisit]
        self.t0 = params[data.par_order['t0']*data.nvisit:(1 + data.par_order['t0'])*data.nvisit]
        self.t_secondary = params[data.par_order['t_secondary']*data.nvisit:(1 + data.par_order['t_secondary'])*data.nvisit]
        self.w = params[data.par_order['w']*data.nvisit:(1 + data.par_order['w'])*data.nvisit]
        self.a = params[data.par_order['a']*data.nvisit:(1 + data.par_order['a'])*data.nvisit]
        self.inc = params[data.par_order['inc']*data.nvisit:(1 + data.par_order['inc'])*data.nvisit]
        self.rp = params[data.par_order['rp']*data.nvisit:(1 + data.par_order['rp'])*data.nvisit]
        self.fp = params[data.par_order['fp']*data.nvisit:(1 + data.par_order['fp'])*data.nvisit]
        self.u1 = params[data.par_order['u1']*data.nvisit:(1 + data.par_order['u1'])*data.nvisit]
        self.u2 = params[data.par_order['u2']*data.nvisit:(1 + data.par_order['u2'])*data.nvisit]
        self.ecc = params[data.par_order['ecc']*data.nvisit:(1 + data.par_order['ecc'])*data.nvisit]
        self.c = params[data.par_order['c']*data.nvisit:(1 + data.par_order['c'])*data.nvisit]
        self.v = params[data.par_order['v']*data.nvisit:(1 + data.par_order['v'])*data.nvisit]
        self.v2 = params[data.par_order['v2']*data.nvisit:(1 + data.par_order['v2'])*data.nvisit]
        self.r1 = params[data.par_order['r1']*data.nvisit:(1 + data.par_order['r1'])*data.nvisit]
        self.r2 = params[data.par_order['r2']*data.nvisit:(1 + data.par_order['r2'])*data.nvisit]
        self.r3 = params[data.par_order['r3']*data.nvisit:(1 + data.par_order['r3'])*data.nvisit]
        self.scale = params[data.par_order['scale']*data.nvisit:(1 + data.par_order['scale'])*data.nvisit]
        self.a1 = params[data.par_order['a1']*data.nvisit:(1 + data.par_order['a1'])*data.nvisit]
        self.omega1 = params[data.par_order['omega1']*data.nvisit:(1 + data.par_order['omega1'])*data.nvisit]
        self.phi1 = params[data.par_order['phi1']*data.nvisit:(1 + data.par_order['phi1'])*data.nvisit]
        self.a2 = params[data.par_order['a2']*data.nvisit:(1 + data.par_order['a2'])*data.nvisit]
        self.omega2 = params[data.par_order['omega2']*data.nvisit:(1 + data.par_order['omega2'])*data.nvisit]
        self.phi2 = params[data.par_order['phi2']*data.nvisit:(1 + data.par_order['phi2'])*data.nvisit]
        self.a3 = params[data.par_order['a3']*data.nvisit:(1 + data.par_order['a3'])*data.nvisit]
        self.omega3 = params[data.par_order['omega3']*data.nvisit:(1 + data.par_order['omega3'])*data.nvisit]
        self.phi3 = params[data.par_order['phi3']*data.nvisit:(1 + data.par_order['phi3'])*data.nvisit]
        self.trap_pop_s = params[data.par_order['trap_pop_s']*data.nvisit:(1 + data.par_order['trap_pop_s'])*data.nvisit]
        self.trap_pop_f = params[data.par_order['trap_pop_f']*data.nvisit:(1 + data.par_order['trap_pop_f'])*data.nvisit]
        self.xshift = params[data.par_order['xshift']*data.nvisit:(1 + data.par_order['xshift'])*data.nvisit]
        self.yshift = params[data.par_order['yshift']*data.nvisit:(1 + data.par_order['yshift'])*data.nvisit]

def PrintParams(m, data): 
    print "per\t", m.params[data.par_order['per']*data.nvisit:(1 + data.par_order['per'])*data.nvisit]
    print "t0\t", m.params[data.par_order['t0']*data.nvisit:(1 + data.par_order['t0'])*data.nvisit]
    print "t_s\t", m.params[data.par_order['t_secondary']*data.nvisit:(1 + data.par_order['t_secondary'])*data.nvisit]
    print "w\t", m.params[data.par_order['w']*data.nvisit:(1 + data.par_order['w'])*data.nvisit]
    print "a\t", m.params[data.par_order['a']*data.nvisit:(1 + data.par_order['a'])*data.nvisit]
    print "inc\t", m.params[data.par_order['inc']*data.nvisit:(1 + data.par_order['inc'])*data.nvisit]
    print "rp\t", m.params[data.par_order['rp']*data.nvisit:(1 + data.par_order['rp'])*data.nvisit]
    print "fp\t", m.params[data.par_order['fp']*data.nvisit:(1 + data.par_order['fp'])*data.nvisit]
    print "u1\t", m.params[data.par_order['u1']*data.nvisit:(1 + data.par_order['u1'])*data.nvisit]
    print "u2\t", m.params[data.par_order['u2']*data.nvisit:(1 + data.par_order['u2'])*data.nvisit]
    print "ecc\t", m.params[data.par_order['ecc']*data.nvisit:(1 + data.par_order['ecc'])*data.nvisit]
    print "c\t", m.params[data.par_order['c']*data.nvisit:(1 + data.par_order['c'])*data.nvisit]
    print "v\t", m.params[data.par_order['v']*data.nvisit:(1 + data.par_order['v'])*data.nvisit]
    print "v2\t",  m.params[data.par_order['v2']*data.nvisit:(1 + data.par_order['v2'])*data.nvisit]
    print "r1\t", m.params[data.par_order['r1']*data.nvisit:(1 + data.par_order['r1'])*data.nvisit]
    print "r2\t", m.params[data.par_order['r2']*data.nvisit:(1 + data.par_order['r2'])*data.nvisit]
    print "r3\t", m.params[data.par_order['r3']*data.nvisit:(1 + data.par_order['r3'])*data.nvisit]
    print "scale\t", m.params[data.par_order['scale']*data.nvisit:(1 + data.par_order['scale'])*data.nvisit]
    print "a1\t", m.params[data.par_order['a1']*data.nvisit:(1 + data.par_order['a1'])*data.nvisit]
    print "omega1\t", m.params[data.par_order['omega1']*data.nvisit:(1 + data.par_order['omega1'])*data.nvisit]
    print "phi1\t", m.params[data.par_order['phi1']*data.nvisit:(1 + data.par_order['phi1'])*data.nvisit]
    print "a2\t", m.params[data.par_order['a2']*data.nvisit:(1 + data.par_order['a2'])*data.nvisit]
    print "omega2\t", m.params[data.par_order['omega2']*data.nvisit:(1 + data.par_order['omega2'])*data.nvisit]
    print "phi2\t", m.params[data.par_order['phi2']*data.nvisit:(1 + data.par_order['phi2'])*data.nvisit]
    print "a3\t", m.params[data.par_order['a3']*data.nvisit:(1 + data.par_order['a3'])*data.nvisit]
    print "omega3\t", m.params[data.par_order['omega3']*data.nvisit:(1 + data.par_order['omega3'])*data.nvisit]
    print "phi3\t", m.params[data.par_order['phi3']*data.nvisit:(1 + data.par_order['phi3'])*data.nvisit]
    print "trap_pop_s\t", m.params[data.par_order['trap_pop_s']*data.nvisit:(1 + data.par_order['trap_pop_s'])*data.nvisit]
    print "trap_pop_f\t", m.params[data.par_order['trap_pop_f']*data.nvisit:(1 + data.par_order['trap_pop_f'])*data.nvisit]
    print "dTrap_s\t", m.params[data.par_order['dTrap_s']*data.nvisit:(1 + data.par_order['dTrap_s'])*data.nvisit]
    print "dTrap_f\t", m.params[data.par_order['dTrap_f']*data.nvisit:(1 + data.par_order['dTrap_f'])*data.nvisit]
    print "xshift\t", m.params[data.par_order['xshift']*data.nvisit:(1 + data.par_order['xshift'])*data.nvisit]
    print "yshift\t", m.params[data.par_order['yshift']*data.nvisit:(1 + data.par_order['yshift'])*data.nvisit]
    print "perror", m.perror

