class FormatParams: 
    """
    doc
    """
    def __init__(self, params, data):
        self.per = params[data.par_order['per']*data.nvisit:(1 + data.par_order['per'])*data.nvisit]
        self.t0 = params[data.par_order['t0']*data.nvisit:(1 + data.par_order['t0'])*data.nvisit]
        self.t_secondary = params[data.par_order['t_secondary']*data.nvisit:(1 + data.par_order['t_secondary'])*data.nvisit]
        self.w = params[data.par_order['w']*data.nvisit:(1 + data.par_order['w'])*data.nvisit]
        self.a = params[data.par_order['a']*data.nvisit:(1 + data.par_order['a'])*data.nvisit]
        self.inc = params[data.par_order['inc']*data.nvisit:(1 + data.par_order['inc'])*data.nvisit]
        self.rp = params[data.par_order['rp']*data.nvisit:(1 + data.par_order['rp'])*data.nvisit]
        self.fp = params[data.par_order['fp']*data.nvisit:(1 + data.par_order['fp'])*data.nvisit]
        self.u1 = params[data.par_order['u1']*data.nvisit:(1 + data.par_order['u1'])*data.nvisit]
        self.u2 = params[data.par_order['u2']*data.nvisit:(1 + data.par_order['u2'])*data.nvisit]
        self.ecc = params[data.par_order['ecc']*data.nvisit:(1 + data.par_order['ecc'])*data.nvisit]
        self.c = params[data.par_order['c']*data.nvisit:(1 + data.par_order['c'])*data.nvisit]
        self.v = params[data.par_order['v']*data.nvisit:(1 + data.par_order['v'])*data.nvisit]
        self.v2 = params[data.par_order['v2']*data.nvisit:(1 + data.par_order['v2'])*data.nvisit]
        self.r1 = params[data.par_order['r1']*data.nvisit:(1 + data.par_order['r1'])*data.nvisit]
        self.r2 = params[data.par_order['r2']*data.nvisit:(1 + data.par_order['r2'])*data.nvisit]
        self.r3 = params[data.par_order['r3']*data.nvisit:(1 + data.par_order['r3'])*data.nvisit]
        self.scale = params[data.par_order['scale']*data.nvisit:(1 + data.par_order['scale'])*data.nvisit]
        self.amp1 = params[data.par_order['amp1']*data.nvisit:(1 + data.par_order['amp1'])*data.nvisit]
        self.theta1 = params[data.par_order['theta1']*data.nvisit:(1 + data.par_order['theta1'])*data.nvisit]
        self.amp2 = params[data.par_order['amp2']*data.nvisit:(1 + data.par_order['amp2'])*data.nvisit]
        self.theta2 = params[data.par_order['theta2']*data.nvisit:(1 + data.par_order['theta2'])*data.nvisit]
        self.E_s = params[data.par_order['E_s']*data.nvisit:(1 + data.par_order['E_s'])*data.nvisit]
        self.E_f = params[data.par_order['E_f']*data.nvisit:(1 + data.par_order['E_f'])*data.nvisit]
        self.eta_s = params[data.par_order['eta_s']*data.nvisit:(1 + data.par_order['eta_s'])*data.nvisit]
        self.eta_f = params[data.par_order['eta_f']*data.nvisit:(1 + data.par_order['eta_f'])*data.nvisit]
        self.tau_s = params[data.par_order['tau_s']*data.nvisit:(1 + data.par_order['tau_s'])*data.nvisit]
        self.tau_f = params[data.par_order['tau_f']*data.nvisit:(1 + data.par_order['tau_f'])*data.nvisit]
        self.E_s0 = params[data.par_order['E_s0']*data.nvisit:(1 + data.par_order['E_s0'])*data.nvisit]
        self.E_f0 = params[data.par_order['E_f0']*data.nvisit:(1 + data.par_order['E_f0'])*data.nvisit]
        self.f = params[data.par_order['f']*data.nvisit:(1 + data.par_order['f'])*data.nvisit]
        self.A1 = params[data.par_order['A1']*data.nvisit:(1 + data.par_order['A1'])*data.nvisit]
        self.P1 = params[data.par_order['P1']*data.nvisit:(1 + data.par_order['P1'])*data.nvisit]
        self.phi1 = params[data.par_order['phi1']*data.nvisit:(1 + data.par_order['phi1'])*data.nvisit]
        self.A2 = params[data.par_order['A2']*data.nvisit:(1 + data.par_order['A2'])*data.nvisit]
        self.P2 = params[data.par_order['P2']*data.nvisit:(1 + data.par_order['P2'])*data.nvisit]
        self.phi2 = params[data.par_order['phi2']*data.nvisit:(1 + data.par_order['phi2'])*data.nvisit]

def PrintParams(m, data): 
    print "per\t", m.params[data.par_order['per']*data.nvisit:(1 + data.par_order['per'])*data.nvisit]
    print "t0\t", m.params[data.par_order['t0']*data.nvisit:(1 + data.par_order['t0'])*data.nvisit]
    print "t_s\t", m.params[data.par_order['t_secondary']*data.nvisit:(1 + data.par_order['t_secondary'])*data.nvisit]
    print "w\t", m.params[data.par_order['w']*data.nvisit:(1 + data.par_order['w'])*data.nvisit]
    print "a\t", m.params[data.par_order['a']*data.nvisit:(1 + data.par_order['a'])*data.nvisit]
    print "inc\t", m.params[data.par_order['inc']*data.nvisit:(1 + data.par_order['inc'])*data.nvisit]
    print "rp\t", m.params[data.par_order['rp']*data.nvisit:(1 + data.par_order['rp'])*data.nvisit]
    print "fp\t", m.params[data.par_order['fp']*data.nvisit:(1 + data.par_order['fp'])*data.nvisit]
    print "u1\t", m.params[data.par_order['u1']*data.nvisit:(1 + data.par_order['u1'])*data.nvisit]
    print "u2\t", m.params[data.par_order['u2']*data.nvisit:(1 + data.par_order['u2'])*data.nvisit]
    print "ecc\t", m.params[data.par_order['ecc']*data.nvisit:(1 + data.par_order['ecc'])*data.nvisit]
    print "c\t", m.params[data.par_order['c']*data.nvisit:(1 + data.par_order['c'])*data.nvisit]
    print "v\t", m.params[data.par_order['v']*data.nvisit:(1 + data.par_order['v'])*data.nvisit]
    print "v2\t",  m.params[data.par_order['v2']*data.nvisit:(1 + data.par_order['v2'])*data.nvisit]
    print "r1\t", m.params[data.par_order['r1']*data.nvisit:(1 + data.par_order['r1'])*data.nvisit]
    print "r2\t", m.params[data.par_order['r2']*data.nvisit:(1 + data.par_order['r2'])*data.nvisit]
    print "r3\t", m.params[data.par_order['r3']*data.nvisit:(1 + data.par_order['r3'])*data.nvisit]
    print "scale\t", m.params[data.par_order['scale']*data.nvisit:(1 + data.par_order['scale'])*data.nvisit]
    print "amp1\t", m.params[data.par_order['amp1']*data.nvisit:(1 + data.par_order['amp1'])*data.nvisit]
    print "theta1\t", m.params[data.par_order['theta1']*data.nvisit:(1 + data.par_order['theta1'])*data.nvisit]
    print "amp2\t", m.params[data.par_order['amp2']*data.nvisit:(1 + data.par_order['amp2'])*data.nvisit]
    print "theta2\t", m.params[data.par_order['theta2']*data.nvisit:(1 + data.par_order['theta2'])*data.nvisit]
    print "E_s\t", m.params[data.par_order['E_s']*data.nvisit:(1 + data.par_order['E_s'])*data.nvisit]
    print "E_f\t", m.params[data.par_order['E_f']*data.nvisit:(1 + data.par_order['E_f'])*data.nvisit]
    print "eta_s\t", m.params[data.par_order['eta_s']*data.nvisit:(1 + data.par_order['eta_s'])*data.nvisit]
    print "eta_f\t", m.params[data.par_order['eta_f']*data.nvisit:(1 + data.par_order['eta_f'])*data.nvisit]
    print "tau_s\t", m.params[data.par_order['tau_s']*data.nvisit:(1 + data.par_order['tau_s'])*data.nvisit]
    print "tau_f\t", m.params[data.par_order['tau_f']*data.nvisit:(1 + data.par_order['tau_f'])*data.nvisit]
    print "E_s0\t", m.params[data.par_order['E_s0']*data.nvisit:(1 + data.par_order['E_s0'])*data.nvisit]
    print "E_f0\t", m.params[data.par_order['E_f0']*data.nvisit:(1 + data.par_order['E_f0'])*data.nvisit]
    print "f\t", m.params[data.par_order['f']*data.nvisit:(1 + data.par_order['f'])*data.nvisit]
    print "A1\t", m.params[data.par_order['A1']*data.nvisit:(1 + data.par_order['A1'])*data.nvisit]
    print "P1\t", m.params[data.par_order['P1']*data.nvisit:(1 + data.par_order['P1'])*data.nvisit]
    print "phi1\t", m.params[data.par_order['phi1']*data.nvisit:(1 + data.par_order['phi1'])*data.nvisit]
    print "A2\t", m.params[data.par_order['A2']*data.nvisit:(1 + data.par_order['A2'])*data.nvisit]
    print "P2\t", m.params[data.par_order['P2']*data.nvisit:(1 + data.par_order['P2'])*data.nvisit]
    print "phi2\t", m.params[data.par_order['phi2']*data.nvisit:(1 + data.par_order['phi2'])*data.nvisit]
    print "perror", m.perror

